insert into public.resorts (
  name,
  property_name,
  slug,
  destination,
  brand,
  region,
  address_line1,
  address_line2,
  city,
  state,
  zip,
  country,
  description,
  description_short,
  description_long,
  amenities,
  hero_image_url,
  gallery_images,
  active,
  is_published,
  has_water_park,
  has_beach_access,
  is_ranch,
  is_orlando_concierge_supported,
  official_url,
  min_checkin_age_default,
  min_checkin_age_override,
  from_rate_reference,
  from_rate_currency,
  from_rate_source,
  reference_notes
)
values
(
  'Harbour Beach Oceanfront Villas (Daytona)',
  'Westgate Harbour Beach Resort',
  'harbour-beach-resort',
  'Daytona Beach, Florida',
  'Westgate',
  'Beach & Coast',
  '701 S Atlantic Ave',
  'Unit 811',
  'Daytona Beach',
  'FL',
  '32118',
  'US',
  'Oceanfront condo-style stay in Daytona Beach with kitchen-ready layouts and balcony vibes. Built for quick getaways and simple beach days.',
  'Oceanfront condo-style Daytona Beach stay with space to spread out, kitchen-ready layouts, and easy access to the sand.',
  null,
  '[]'::jsonb,
  null,
  '[]'::jsonb,
  true,
  false,
  false,
  true,
  false,
  false,
  'https://www.travelweekly.com/Hotels/Daytona-Beach-FL/Harbour-Beach-Resort-p4216735',
  21,
  null,
  79.00,
  'USD',
  'Travel Weekly',
  'Published rate range reference: $79–$219.'
),
(
  'Point Brown Coastal Retreat (Ocean Shores)',
  'Point Brown (Westgate)',
  'point-brown-coastal-retreat',
  'Ocean Shores, Washington',
  'Westgate',
  'Pacific Northwest',
  'Point Brown Ave NE',
  null,
  'Ocean Shores',
  'WA',
  '98569',
  'US',
  'Pacific Northwest coastal reset in Ocean Shores with easy beach access and a low-key small-town feel. Ideal for weekend escapes and cool-weather sunsets.',
  'Pacific Northwest coastal base with easy beach access, a relaxed pace, and quick drives to shops and dining in Ocean Shores.',
  null,
  '[]'::jsonb,
  null,
  '[]'::jsonb,
  true,
  false,
  false,
  true,
  false,
  false,
  'https://www.westgateresorts.com/hotels/washington/ocean-shores/point-brown/overview/',
  21,
  null,
  null,
  'USD',
  null,
  null
),
(
  'Pono Kai Beachside Suites (Kapaʻa, Kauaʻi)',
  'Pono Kai Resort',
  'pono-kai-beachside-suites',
  'Kapaa, Hawaii',
  'Pono Kai',
  'Hawaii',
  '4-1250 Kuhio Hwy',
  null,
  'Kapaa',
  'HI',
  '96746',
  'US',
  'Beachside suites in Kapaʻa that work as an easy home base for exploring Kauaʻi. Built for travelers who want more space than a hotel and a relaxed island pace.',
  'Beachside Kauaʻi base in Kapaʻa with suite layouts and a relaxed “home base” feel for exploring the island.',
  null,
  '[]'::jsonb,
  null,
  '[]'::jsonb,
  true,
  false,
  false,
  true,
  false,
  false,
  'https://ponokai.com/about-pono-kai/',
  21,
  null,
  null,
  'USD',
  null,
  null
),
(
  'River Terrace Downtown Gatlinburg',
  'River Terrace Resort & Convention Center (Westgate)',
  'river-terrace-resort-and-convention-center',
  'Gatlinburg, Tennessee',
  'Westgate',
  'Mountains',
  '240 River Rd',
  null,
  'Gatlinburg',
  'TN',
  '37738',
  'US',
  'Downtown Gatlinburg stay on the river with quick access to attractions, the trolley, and Smoky Mountain day trips. A convenient base that keeps driving to a minimum.',
  'Walkable Gatlinburg riverfront base near attractions and Smoky Mountain day trips, designed for easy in-and-out logistics.',
  null,
  '[]'::jsonb,
  null,
  '[]'::jsonb,
  true,
  false,
  false,
  false,
  false,
  false,
  'https://www.westgateresorts.com/hotels/tennessee/gatlinburg/river-terrace-resort-convention-center/overview-your-stay/',
  21,
  null,
  33.00,
  'USD',
  'Westgate Reservations',
  'Published deposit note reference (example): $50 credit card / $200 cash.'
),
(
  'Santa Fe Plaza Boutique Escape',
  'Rosewood Inn of the Anasazi',
  'santa-fe-plaza-boutique-escape',
  'Santa Fe, New Mexico',
  'Rosewood',
  'Southwest',
  '113 Washington Ave',
  null,
  'Santa Fe',
  'NM',
  '87501',
  'US',
  'Premium Santa Fe boutique stay in the historic plaza district with high-touch service and Southwest design details. Built for milestone trips and executive escapes where the hotel experience matters as much as the destination.',
  'Premium Santa Fe boutique stay near the historic plaza, built for milestone trips and high-touch service expectations.',
  null,
  '[]'::jsonb,
  null,
  '[]'::jsonb,
  true,
  false,
  false,
  false,
  false,
  false,
  'https://www.rosewoodhotels.com/en/inn-of-the-anasazi-santa-fe',
  21,
  null,
  null,
  'USD',
  null,
  'Luxury pricing varies heavily by season; confirm live rates before publishing a hard “from” price.'
),
(
  'Blue Tree Orlando Family Suites',
  'Westgate Blue Tree Resort',
  'westgate-blue-tree-resort',
  'Lake Buena Vista, Florida',
  'Westgate',
  'Orlando',
  '12007 Cypress Run Road',
  null,
  'Lake Buena Vista',
  'FL',
  '32836',
  'US',
  'Family-friendly villa-style resort minutes from Disney Springs with multiple pools and an easy home-base layout. Great for park-heavy itineraries that still need downtime and kitchen convenience.',
  'Family-friendly Orlando-area villa resort near Disney Springs with kitchen convenience, pools, and quick park access.',
  null,
  '[]'::jsonb,
  null,
  '[]'::jsonb,
  true,
  false,
  false,
  false,
  false,
  true,
  'https://www.westgateresorts.com/hotels/florida/orlando/westgate-blue-tree-resort/overview/',
  21,
  null,
  null,
  'USD',
  null,
  'Published policy reference: resort fee and deposit rules may apply at check-in.'
),
(
  'Branson Lakes Hideaway',
  'Westgate Branson Lakes Resort',
  'westgate-branson-lakes-resort',
  'Hollister, Missouri',
  'Westgate',
  'Branson',
  '750 Emerald Pointe Dr',
  null,
  'Hollister',
  'MO',
  '65672',
  'US',
  'Spacious villa-style retreat near Table Rock Lake and Branson entertainment. Good for families and groups who want larger floorplans and easy access to shows and lake time.',
  'Villa-style Branson-area stay near Table Rock Lake, designed for families and groups who want space and simple access to shows.',
  null,
  '[]'::jsonb,
  null,
  '[]'::jsonb,
  true,
  false,
  false,
  false,
  false,
  false,
  'https://www.westgatereservations.com/resorts/westgate-branson-lakes-resort/accommodations/',
  21,
  null,
  40.00,
  'USD',
  'Westgate Reservations',
  null
),
(
  'Branson Woods Cabins & Villas',
  'Westgate Branson Woods Resort',
  'westgate-branson-woods-resort',
  'Branson, Missouri',
  'Westgate',
  'Branson',
  '2201 Roark Valley Rd',
  null,
  'Branson',
  'MO',
  '65616',
  'US',
  'Wooded cabins-and-villas vibe close to Branson attractions, ideal for groups who want a quieter setting after busy days. A solid option for multi-bedroom layouts and relaxed evenings.',
  'Wooded Branson cabins-and-villas vibe for groups who want a quieter setting while staying close to shows and dining.',
  null,
  '[]'::jsonb,
  null,
  '[]'::jsonb,
  true,
  false,
  false,
  false,
  false,
  false,
  'https://www.westgatereservations.com/resorts/westgate-branson-woods-resort/accommodations/',
  21,
  null,
  40.00,
  'USD',
  'Westgate Reservations',
  null
),
(
  'Cocoa Beach Resort + Water Play',
  'Westgate Cocoa Beach Resort',
  'westgate-cocoa-beach-resort',
  'Cocoa Beach, Florida',
  'Westgate',
  'Beach & Coast',
  '3550 N Atlantic Ave',
  null,
  'Cocoa Beach',
  'FL',
  '32931',
  'US',
  'Beach-forward suites on Florida’s Space Coast—perfect for surf days, cruise add-ons, and launch-weekend itineraries. Designed as a simple coastal reset with room to spread out.',
  'Space Coast beach-forward suites built for surf days, launch weekends, and quick coastal resets with room to spread out.',
  null,
  '[]'::jsonb,
  null,
  '[]'::jsonb,
  true,
  false,
  false,
  true,
  false,
  false,
  'https://www.westgateresorts.com/hotels/florida/cocoa-beach',
  21,
  null,
  309.00,
  'USD',
  'Westgate',
  'Reference: “tonight’s rates from $309/night” (subject to change).'
),
(
  'Flamingo Bay Villa Resort (Vegas)',
  'Westgate Flamingo Bay Resort',
  'westgate-flamingo-bay-resort',
  'Las Vegas, Nevada',
  'Westgate',
  'Las Vegas',
  '5625 W Flamingo Rd',
  null,
  'Las Vegas',
  'NV',
  '89103',
  'US',
  'Villa-style Las Vegas base away from the Strip, built for guests who want quieter nights and more space. Works well for longer stays that prefer a residential feel over casino-floor energy.',
  'Villa-style Las Vegas base with more space and a quieter pace, designed for longer stays and off-Strip convenience.',
  null,
  '[]'::jsonb,
  null,
  '[]'::jsonb,
  true,
  false,
  false,
  false,
  false,
  false,
  'https://www.westgateresorts.com/hotels/nevada/las-vegas/westgate-flamingo-bay-resort/',
  21,
  null,
  null,
  'USD',
  null,
  null
),
(
  'Historic Williamsburg Stay',
  'Westgate Historic Williamsburg Resort',
  'westgate-historic-williamsburg-resort',
  'Williamsburg, Virginia',
  'Westgate',
  'East Coast',
  '1324 Richmond Rd',
  null,
  'Williamsburg',
  'VA',
  '23185',
  'US',
  'History-first destination base near Colonial Williamsburg with easy access to family attractions. Best for trips that want a calm reset between day plans.',
  'History-first Williamsburg base near Colonial Williamsburg and family attractions, built for easy day-trip pacing.',
  null,
  '[]'::jsonb,
  null,
  '[]'::jsonb,
  true,
  false,
  false,
  false,
  false,
  false,
  'https://www.westgatereservations.com/resorts/westgate-historic-williamsburg-resort/location/',
  21,
  null,
  40.00,
  'USD',
  'Westgate Reservations',
  null
),
(
  'Orlando Lakes Resort + Water Park',
  'Westgate Lakes Resort & Spa',
  'westgate-lakes-resort-and-spa',
  'Orlando, Florida',
  'Westgate',
  'Orlando',
  '9500 Turkey Lake Rd',
  null,
  'Orlando',
  'FL',
  '32819',
  'US',
  'Big Orlando resort footprint with on-site amenities and room to spread out near the parks. Great for families who want resort-day flexibility alongside park-heavy itineraries.',
  'Big Orlando resort near the parks with on-site amenities and resort-day flexibility for families and groups.',
  null,
  '[]'::jsonb,
  null,
  '[]'::jsonb,
  true,
  false,
  true,
  false,
  false,
  true,
  'https://www.westgateresorts.com/hotels/florida/orlando/westgate-lakes-resort/overview/',
  21,
  null,
  null,
  'USD',
  null,
  'Published policy reference: resort fee and deposit rules may apply at check-in.'
),
(
  'Vegas Resort & Casino Stay',
  'Westgate Las Vegas Resort & Casino',
  'westgate-las-vegas-resort-and-casino',
  'Las Vegas, Nevada',
  'Westgate',
  'Las Vegas',
  '3000 Paradise Rd',
  null,
  'Las Vegas',
  'NV',
  '89109',
  'US',
  'Full-service Las Vegas resort positioned for conventions and event weekends, with fast access to major corridors. A strong fit for travelers who want a classic Vegas property with simple logistics.',
  'Full-service Las Vegas resort near convention/event corridors, built for convention trips, sports weekends, and simple logistics.',
  null,
  '[]'::jsonb,
  null,
  '[]'::jsonb,
  true,
  false,
  false,
  false,
  false,
  false,
  'https://www.westgateresorts.com/hotels/nevada/las-vegas/westgate-las-vegas-resort-casino/overview-your-stay/',
  21,
  18,
  null,
  'USD',
  null,
  'Published policy reference indicates 18+ check-in age and resort fee/deposit details.'
),
(
  'Myrtle Beach Oceanfront',
  'Westgate Myrtle Beach Oceanfront Resort',
  'westgate-myrtle-beach-oceanfront-resort',
  'Myrtle Beach, South Carolina',
  'Westgate',
  'Beach & Coast',
  '415 S Ocean Blvd',
  null,
  'Myrtle Beach',
  'SC',
  '29577',
  'US',
  'Oceanfront family-resort energy with quick access to boardwalk attractions and dining. Built for beach days, pool downtime, and easy walks back to the room.',
  'Oceanfront Myrtle Beach base for beach days and family downtime, with easy access to boardwalk attractions and dining.',
  null,
  '[]'::jsonb,
  null,
  '[]'::jsonb,
  true,
  false,
  false,
  true,
  false,
  false,
  'https://www.westgatereservations.com/resorts/westgate-myrtle-beach/amenities/',
  21,
  null,
  75.00,
  'USD',
  'Westgate Reservations',
  null
),
(
  'Painted Mountain Golf Getaway',
  'Westgate Painted Mountain Golf Resort',
  'westgate-painted-mountain-golf-resort',
  'Mesa, Arizona',
  'Westgate',
  'Arizona',
  '6302 E McKellips Rd',
  null,
  'Mesa',
  'AZ',
  '85215',
  'US',
  'Desert-sun getaway in Mesa with golf-adjacent positioning and easy access to greater Phoenix. Ideal for relaxed long weekends and winter sun trips.',
  'Mesa desert-sun base with golf-adjacent positioning, built for relaxed long weekends and winter sun trips.',
  null,
  '[]'::jsonb,
  null,
  '[]'::jsonb,
  true,
  false,
  false,
  false,
  false,
  false,
  'https://www.westgateresorts.com/hotels/arizona/mesa/westgate-painted-mountain-golf-resort/pad/',
  21,
  null,
  null,
  'USD',
  null,
  null
),
(
  'Westgate Palace (I‑Drive) 2BR Suites',
  'Westgate Palace Resort',
  'westgate-palace',
  'Orlando, Florida',
  'Westgate',
  'Orlando',
  '6145 Carrier Dr',
  null,
  'Orlando',
  'FL',
  '32819',
  'US',
  'All-suite Orlando base near I‑Drive and the Universal corridor, designed for groups who want space and a straightforward commute. Two-bedroom layouts make it easy to travel with family or friends.',
  'All-suite Orlando base near I‑Drive for groups who want two-bedroom space and straightforward park logistics.',
  null,
  '[]'::jsonb,
  null,
  '[]'::jsonb,
  true,
  false,
  false,
  false,
  false,
  true,
  'https://www.westgatereservations.com/resorts/westgate-palace/location/',
  21,
  null,
  95.00,
  'USD',
  'Westgate Reservations',
  null
),
(
  'Park City Ski‑In/Ski‑Out Luxury',
  'Westgate Park City Resort & Spa',
  'westgate-park-city-resort-and-spa',
  'Park City, Utah',
  'Westgate',
  'Park City',
  '3000 Canyons Resort Dr',
  null,
  'Park City',
  'UT',
  '84098',
  'US',
  'Mountain luxury base in Canyons Village with ski-season convenience and spa-style downtime. Best for winter trips and premium stays that want the resort experience built in.',
  'Park City mountain luxury base in Canyons Village with ski-season convenience and spa-style downtime.',
  null,
  '[]'::jsonb,
  null,
  '[]'::jsonb,
  true,
  false,
  false,
  false,
  false,
  false,
  'https://www.westgateresorts.com/hotels/utah/park-city/westgate-park-city-resort/',
  21,
  null,
  null,
  'USD',
  null,
  null
),
(
  'River Ranch Dude Ranch + Glamping',
  'Westgate River Ranch Resort & Rodeo',
  'westgate-river-ranch-resort-and-rodeo',
  'River Ranch, Florida',
  'Westgate',
  'River Ranch',
  '3200 River Ranch Blvd',
  null,
  'River Ranch',
  'FL',
  '33867',
  'US',
  'Florida ranch + rodeo style weekend with outdoor activities and a totally different pace from typical resorts. Great for families and groups looking for glamping energy and wide-open space.',
  'Florida ranch + rodeo style weekend with outdoor activities, glamping energy, and a totally different pace from typical resorts.',
  null,
  '[]'::jsonb,
  null,
  '[]'::jsonb,
  true,
  false,
  false,
  false,
  true,
  false,
  'https://www.westgateresorts.com/hotels/florida/river-ranch/westgate-river-ranch-resort/',
  21,
  null,
  25.00,
  'USD',
  'Westgate Reservations',
  'Reference: “From $25/night” (subject to change).'
)
on conflict (slug) do update
set
  name = excluded.name,
  property_name = excluded.property_name,
  destination = excluded.destination,
  brand = excluded.brand,
  region = excluded.region,
  address_line1 = excluded.address_line1,
  address_line2 = excluded.address_line2,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  description = excluded.description,
  description_short = excluded.description_short,
  description_long = excluded.description_long,
  amenities = excluded.amenities,
  hero_image_url = excluded.hero_image_url,
  gallery_images = excluded.gallery_images,
  active = excluded.active,
  is_published = excluded.is_published,
  has_water_park = excluded.has_water_park,
  has_beach_access = excluded.has_beach_access,
  is_ranch = excluded.is_ranch,
  is_orlando_concierge_supported = excluded.is_orlando_concierge_supported,
  official_url = excluded.official_url,
  min_checkin_age_default = excluded.min_checkin_age_default,
  min_checkin_age_override = excluded.min_checkin_age_override,
  from_rate_reference = excluded.from_rate_reference,
  from_rate_currency = excluded.from_rate_currency,
  from_rate_source = excluded.from_rate_source,
  reference_notes = excluded.reference_notes,
  updated_at = now();

